import type { BotDifficulty, BotMind } from '@moley/game-core';
import type { BotPersonality, ChatMessage, DrawingPayload, FeatureFlags, GameSettings, GameStage, PlayerKind, ReactionSummary, RoundHistory, RoundResult, VoteRevealItem } from '@moley/shared';
import type { WordEntry } from '@moley/word-packs';

export type StoredPlayer = {
  id: string;
  name: string;
  kind: PlayerKind;
  reconnectToken: string;
  score: number;
  roundGain: number;
  host: boolean;
  connected: boolean;
  joinedAt: number;
  lastSeen: number;
  reservedUntil: number | null;
  ready: boolean;
  role: 'innocent' | 'mole' | 'spectator' | null;
  moleRounds: number[];
  clue: string | null;
  clueDrawing: DrawingPayload | null;
  clueRevealed: boolean;
  clueSkipped: boolean;
  vote: string | null;
  guess: string | null;
  guessCorrect?: boolean;
  difficulty?: BotDifficulty;
  personality?: BotPersonality;
  botMind?: BotMind;
  queuedForNextRound?: boolean;
  note: string;
  voteConfidence: 1 | 2 | 3 | null;
  prediction: string | null;
  reactionsUsed: string[];
  afk: boolean;
  autopilot: boolean;
};

export type RoomState = {
  initialized: boolean;
  code: string;
  createdAt: number;
  updatedAt: number;
  stage: GameStage;
  roundNumber: number;
  settings: GameSettings;
  players: StoredPlayer[];
  turnOrder: string[];
  currentTurn: number;
  word: WordEntry | null;
  usedWordIds: string[];
  moleIds: string[];
  accusedIds: string[];
  votesRevealed: Record<string, number> | null;
  chat: ChatMessage[];
  timerEndsAt: number | null;
  timerPausedRemaining: number | null;
  result: RoundResult | null;
  winners: string[];
  message: string | null;
  serverSequence: number;
  processedEvents: string[];
  featureFlags: FeatureFlags;
  voteRevealItems: VoteRevealItem[];
  reactions: ReactionSummary;
  history: RoundHistory[];
  chaosModifier: string | null;
  revoteUsed: boolean;
  crowdWords: { playerId: string; word: string }[];
};

export type Env = {
  GAME_ROOMS: DurableObjectNamespace;
  ABUSE_GATE: DurableObjectNamespace;
  ASSETS: Fetcher;
  AI?: Ai;
  AI_MODEL?: string;
  LOAD_TEST?: string;
  FEATURE_FLAGS_JSON?: string;
  KILL_AI?: string;
  KILL_CHAT?: string;
  KILL_CUSTOM_PACKS?: string;
  KILL_DRAWING?: string;
  KILL_SPECTATOR_PREDICTIONS?: string;
  KILL_EXTERNAL_SHARING?: string;
  KILL_COSMETICS?: string;
};
